baseurl = "https://www.thatjoemoore.com"
languageCode = "en"
title = "Joseph's Soapbox"
theme = "kiss"
copyright = "&copy; Joseph Moore 2018"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

pygmentsCodeFences=true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "thatjoemoore"
github = "thatjoemoore"
email = "mail@thatjoemoore.com"
devto = "thatjoemoore"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
